### PR TITLE
Substitute positional arguments with named arguments and introduce type check level option

### PR DESCRIPTION
**Pull request by adamjakab**
Hi @matco,

Thanks for this repo. Amazing job.
I only needed to introduce the type check level option (see my [Issue #3](https://github.com/matco/action-connectiq-tester/issues/3) on the tester action) but in doing so I thought that if you ever want to add more future options (for example: build-only if you don't have tests yet) you'd want to use named arguments. So, here it is. 
I updated the README to reflect the changes and I made sure that backward compatibility with the positional arguments is preserved. Let me know if this is in line with your development plans.

### CODE REVIEW

**Comment by adamjakab** [comment]
Hi @matco! Did you have a chance to review this?

**Comment by matco** [comment]
Hi!

Thanks again for the contribution, it's a great improvement!

I think it's not necessary to keep the backward compatibility. I will be releasing the next version of this Docker image and the associated GitHub Action simultaneously, so we won't have any incompatibility.

Regarding the argument names, I think we should align them with the `monkeyc` compiler for consistency (as described here https://developer.garmin.com/connect-iq/monkey-c/compiler-options):
- `--certificate-path` should be `--private-key`
- `--type-check` should be `--typecheck`

It would be even better to also support the short version of these arguments.

What do you think?

**Comment by adamjakab** [comment]
Hi @matco,

I needed to move forward so I forked both this and the action repo and made changes there. 
Both forks are with the same license and displaying credits to your work. As of now [connectiq-builder](https://github.com/adamjakab/connectiq-builder) is 26 commits ahead of yours and [action-connectic-builder](https://github.com/adamjakab/action-connectiq-builder) is 44 commits ahead. Using these I am now able to do the tests as well as package the Garmin app and add it to the release (see: https://github.com/adamjakab/iHIIT/actions/runs/9628935329). 
You are welcome to re-use any part of that code. 

As it stands now, I am super busy on other projects and I will not be able to work more on this PR.

PS: Good point on aligning the argument names with `monkeyc`.

**Comment by matco** [comment]
Ok, that's fine. I will take a look at your fork.

**Pull request closed without merging**
